name: CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      # 1) Checkout (with submodules)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      # 2) Linux/macOS: install FLTK, TBB via package manager
      - name: Install deps (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          if [ "$(uname)" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libfltk1.3-dev libtbb-dev cmake
          else
            brew update
            brew install fltk tbb cmake
          fi

      # 3) Windows: clone & bootstrap vcpkg
      - name: Bootstrap vcpkg (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics

      # 4) Windows: install FLTK & TBB via vcpkg
      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\vcpkg\vcpkg.exe install fltk tbb --triplet x64-windows

      # 5) Clean old build dir
      - name: Cleanup old build dir
        run: rm -rf build

      # 6) Configure with CMake (pass toolchain on Windows)
      - name: Configure with CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
            $([[ "${{ runner.os }}" == "Windows" ]] && echo "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows")

      # 7) Build
      - name: Build
        run: cmake --build build --config Release

      # 8) List outputs
      - name: List build dir
        run: ls -R build

      # 9) Upload the binary
      - name: Upload shark binary
        uses: actions/upload-artifact@v4
        with:
          name: shark-${{ matrix.os }}
          path: build/shark*
