name: CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      # 1) Checkout (with submodules)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      # 2) Install FLTK & TBB on Linux/macOS
      - name: Install deps (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          if [ "$(uname)" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libfltk1.3-dev libtbb-dev cmake
          else
            brew update
            brew install fltk tbb cmake
          fi

      # 3) Bootstrap & install via vcpkg on Windows
      - name: Cache vcpkg (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-
      - name: Bootstrap vcpkg (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (-not (Test-Path vcpkg/bootstrap-vcpkg.bat)) {
            git clone https://github.com/microsoft/vcpkg.git vcpkg
          }
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\vcpkg\vcpkg.exe install fltk tbb --triplet x64-windows

      # 4) Cleanup old build directory
      - name: Cleanup build dir (Linux/macOS)
        if: runner.os != 'Windows'
        run: rm -rf build
      - name: Cleanup build dir (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: Remove-Item build -Recurse -Force -ErrorAction SilentlyContinue

      # 5) Configure with CMake
      - name: Configure with CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
            $([[ "${{ runner.os }}" == "Windows" ]] && echo "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows" || echo "")

      # 6) Build
      - name: Build
        run: cmake --build build --config Release

      # 7) Inspect outputs
      - name: List build dir
        run: ls -R build

      # 8) Upload the binary
      - name: Upload shark binary
        uses: actions/upload-artifact@v4
        with:
          name: shark-${{ matrix.os }}
          path: build/shark*
