name: CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      # 1) Checkout (with submodules)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      # 2) Linux/macOS deps
      - name: Install deps (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          if [ "$(uname)" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libfltk1.3-dev libtbb-dev cmake
          else
            brew update
            brew install fltk tbb cmake
          fi

      # 3) Bootstrap vcpkg on Windows
      - name: Setup vcpkg (Windows)
        if: runner.os == 'Windows'
        uses: lukka/get-vcpkg@v29

      # 4) Cache vcpkg build artifacts (Windows)
      - name: Cache vcpkg packages (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v3
        with:
          path: |
            vcpkg/installed
            vcpkg/buildtrees
            vcpkg/packages
            vcpkg/archives
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-cache
          restore-keys: |
            ${{ runner.os }}-vcpkg-cache

      # 5) Install FLTK & TBB via vcpkg (Windows)
      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        run: .\vcpkg\vcpkg.exe install fltk tbb --triplet x64-windows

      # 6) Configure: Linux/macOS
      - name: Configure (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      # 7) Configure: Windows (with vcpkg toolchain)
      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release `
             `-DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"

      # 8) Build
      - name: Build
        run: cmake --build build --config Release

      # 9) Inspect outputs
      - name: List build dir
        run: ls -R build

      # 10) Upload the binary
      - name: Upload shark binary
        uses: actions/upload-artifact@v4
        with:
          name: shark-${{ matrix.os }}
          path: build/shark*
